inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-storage.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "support/**/*"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/storage/bucket.rb"
    - "lib/google/cloud/storage/bucket/acl.rb"
    - "lib/google/cloud/storage/file.rb"
    - "lib/google/cloud/storage/file/acl.rb"
    - "lib/google/cloud/storage/service.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-storage.rb"
Style/Documentation:
  Exclude:
    - "lib/google-cloud-storage.rb"
